### ISSUE TITLE
Remote MONGO_URL example

### ISSUE THREAD

**Issue by neurobe** [Mairu/meteor-electrify#2]
Hi Thanks for reviving this project. 
It just worked when I packaged my large Meteor app.

I understand that this package now has the capacity to connect to a remote MongoDB. I tried this..

electrify.son (also tried settings.json)

{ "plugins" : [],
 "MONGO_URL": "mongodb://user:pwd@.....
"MONGO_OPLOG_URL": ......
}
but no success. Is this the correct approach? Perhaps an example?

Given the stated security risks with the above approach, if it is possible to use remote DDP connections instead, I think that would be preferable. Is there a variable for this, or does it need to be hard coded?

Thanks again 
bruce

**Comment by Mairu** [comment]
It is nested as mongo property, so it should be 
```json
{ "plugins" : [],
  "mongo": {
    "MONGO_URL": "mongodb://user:pwd@.....",
    "MONGO_OPLOG_URL": "....."
  } 
}
```

For the DDP connections approach, yes that has to be coded and is no configuration.

**Comment by neurobe** [comment]
OK, that worked thank you. 
Lets see if I can fiddle with remote DDPs. That is more what I am needing I think.

For others looking at this thread, I'll make the point (it is mentioned in the Readme, but took me a little while to understand)...
Once 'electrify' is first run, some files are created that will not be overwritten in future passes, so these files can be edited.
One such file is .electrify/electrify.json and this is where the lines above are inserted.
