### ISSUE TITLE
unable to make this work using a stock Meteor "todos" app

### ISSUE THREAD

**Issue by LDubya** [Mairu/meteor-electrify#3]
Hello, I'm unable to make this work using a stock Meteor "todo's" app.

After creating the stock Meteor todo's app using `meteor create simple-todos`, and installing this package globally, and running `electrify package` (with Electron v7.1.8 and electron-packager v 14.1.1) -- the resulting .app will not run. The window never pops up.

Can you tell me how to make this work?

**Comment by Mairu** [comment]
Hi,
the internal version of electron-packager will be used (it is at v13 for version 4.0.0 of this package).

I tried it locally (Windows 10) with Electron 4 and Electron 7, and both worked.

(First make sure with meteor run, that the application and all needed dependencies are there)
